version: '3.6'

services: 
    #Backend API
    smart-brain-api:
        container_name: backend       
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        environment: 
            POSTGRES_URI: postgres://postgres:0310980@postgres:5432/smart-brain-docker
            REDIS_URI: redis://redis:6379
        links:
            - postgres
            - redis
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/smart-brain-api
    # Postgres
    postgres: 
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 0310980
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports: 
            - "5432:5432"
    # Redis
    redis: 
        image: redis
        ports: 
            - "6379:6379"    